/**
 * Generate and install a `prepare-commit-msg` git hook that fills the commit
 * message with commit-genie's suggestion (only when no message was given).
 */
export const HOOK_MARKER = "# >>> commit-genie hook >>>";

export function hookScript(): string {
  return `#!/bin/sh
${HOOK_MARKER}
# Auto-generated by 'commit-genie --install-hook'. Remove this file to uninstall.
COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"

# Only generate when the user did not supply a message (-m), a template,
# merge, squash, or amend source.
if [ -z "$COMMIT_SOURCE" ]; then
  MSG=$(commit-genie --print 2>/dev/null)
  if [ -n "$MSG" ]; then
    printf '%s\\n\\n%s\\n' "$MSG" "$(cat "$COMMIT_MSG_FILE")" > "$COMMIT_MSG_FILE"
  fi
fi
${HOOK_MARKER.replace(">>>", "<<<")}
`;
}
